name: Bug Report
description: File a bug report
title: "[Bug]: "
labels:
  - "bug"
  - "triage"
assignees:
  - "nicolas377"
  - "Guy-Adler"
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    validations:
      required: false
    attributes:
      label: Description
      description: Explain what's going wrong.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: Explain what you expected to happen.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Actual behavior
      description: Explain what actually happened.
  - type: input
    validations:
      required: true
    attributes:
      label: Operating System
      description: The OS that you were running when you discovered the problem. Include the version number.
  - type: input
    validations:
      required: true
    attributes:
      label: Browser
      description: The OS that you were running when you discovered the problem. Include the version number
  - type: input
    validations:
      required: true
    attributes:
      label: Version
      description: The version of the chrome extension you were running.
