define(function () {
  // left to right, top to bottom on a QWERTY keyboard:
  return {
    // row 1
    Escape: "Escape",
    F1: "F1",
    F2: "F2",
    F3: "F3",
    F4: "F4",
    F5: "F5",
    F6: "F6",
    F7: "F7",
    F8: "F8",
    F9: "F9",
    F10: "F10",
    F11: "F11",
    F12: "F12",
    PrintScreen: "PrintScreen",
    ScrollLock: "ScrollLock",
    Pause: "Pause",
    // row 2
    Backquote: "Backquote",
    Digit1: "1",
    Digit2: "2",
    Digit3: "3",
    Digit4: "4",
    Digit5: "5",
    Digit6: "6",
    Digit7: "7",
    Digit8: "8",
    Digit9: "9",
    Digit0: "0",
    Minus: "-",
    Equal: "=",
    Backspace: "Backspace",
    Insert: "Insert",
    Home: "Home",
    PageUp: "PageUp",
    NumLock: "NumLock",
    NumpadDivide: "/",
    NumpadMultiply: "*",
    NumpadSubtract: "-",
    // row 3
    Tab: "Tab",
    KeyQ: "Q",
    KeyW: "W",
    KeyE: "E",
    KeyR: "R",
    KeyT: "T",
    KeyY: "Y",
    KeyU: "U",
    KeyI: "I",
    KeyO: "O",
    KeyP: "P",
    BracketLeft: "[",
    BracketRight: "]",
    Backslash: "\\",
    Delete: "Delete",
    End: "End",
    PageDown: "PageDown",
    Numpad7: "7",
    Numpad8: "8",
    Numpad9: "9",
    NumpadAdd: "+",
    // row 4
    CapsLock: "CapsLock",
    KeyA: "A",
    KeyS: "S",
    KeyD: "D",
    KeyF: "F",
    KeyG: "G",
    KeyH: "H",
    KeyJ: "J",
    KeyK: "K",
    KeyL: "L",
    Semicolon: ";",
    Quote: "'",
    Enter: "Enter",
    Numpad4: "4",
    Numpad5: "5",
    Numpad6: "6",
    // row 5
    ShiftLeft: "Shift",
    KeyZ: "Z",
    KeyX: "X",
    KeyC: "C",
    KeyV: "V",
    KeyB: "B",
    KeyN: "N",
    KeyM: "M",
    Comma: ",",
    Period: ".",
    Slash: "/",
    ShiftRight: "Shift",
    ArrowUp: "UP ARROW",
    Numpad1: "1",
    Numpad2: "2",
    Numpad3: "3",
    NumpadEnter: "Enter",
    // row 6
    ControlLeft: "Control",
    MetaLeft: "Meta",
    AltLeft: "Alt",
    Space: "Space",
    AltRight: "Alt",
    MetaRight: "Meta",
    ContextMenu: "ContextMenu",
    ControlRight: "Control",
    ArrowLeft: "LEFT ARROW",
    ArrowDown: "DOWN ARROW",
    ArrowRight: "RIGHT ARROW",
    Numpad0: "0",
    NumpadDecimal: ".",
  };
});
