name: Build extension

on:
  workflow_dispatch:
  push:
    paths:
      - 'extension/**'

jobs:
  job_1:
    name: Upload extension as artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Copy extension folder to build enviornment
      - name: Copy to build enviornment
        run: |
          mkdir -p ./build/extension
          cp -rf ./extension/* ./build/extension
        shell: bash

      - name: Upload build enviornment as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-env
          path: build/extension

  job_2:
    name: Compile TS to JS
    needs: job_1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build enviornment
        uses: actions/download-artifact@v2
        with:
          name: build-env
          path: build/extension

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup packages
        run: |
          npm i
          rm -rf extension

      - name: Compile TS files
        run: npx tsc

      - name: Upload build env as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-env
          path: build/extension

  job_3:
    name: Zip built extension
    needs: job_2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build enviornment
        uses: actions/download-artifact@v2
        with:
          name: build-env
          path: build/extension

      - name: Zip folder
        uses: vimtor/action-zip@v1
        with:
          files: build/extension
          dest: build/extension.zip

      - name: Upload build env as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-env
          path: build/extension

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git pull
          git add ./build/extension.zip
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Build extension" -a --allow-empty
            echo "::set-output name=push::true"
          fi
          git push -f
        shell: bash