name: Daily Test

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'

      - name: Install packages
        run: npm i

      - name: Lint
        run: sudo npx eslint

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'

      - name: Install packages
        run: npm i

      - name: Audit for vulnerabilities
        run: sudo npx audit-ci --moderate