name: Nightly actions

on:
  workflow_dispatch:

  schedule:
    - cron: "0 2 * * *"

jobs:
  job_1:
    name: Build airports.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Download airports.csv
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: "https://ourairports.com/data/airports.csv"
          file-name: "airports.csv"
          location: "./data"

      - name: Build extension
        run: npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Build airports.json"
          branch: main
  job_2:
    name: Lock old issues and prs
    runs-on: ubuntu-latest

    steps:
      - name: Lock issues
        uses: dessant/lock-threads@v2
        with:
          issue-exclude-labels: "dependencies"
          issue-lock-labels: "locked"
          pr-lock-labels: "locked"
          issue-lock-inactive-days: 15
          pr-lock-inactive-days: 15
          issue-lock-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
          pr-lock-comment: >
            This pull request has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.

  job_3:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Build docs
        run: |
          npm i
          npm run docs

      - name: Upload docs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/

  job_4:
    name: Commit docs
    runs-on: ubuntu-latest
    needs: job_3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: docs

      - name: Download docs artifact
        uses: actions/download-artifact@v2
        with:
          name: docs

      - name: Commit docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build docs
          branch: docs

  job_5:
    name: Build AP++
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: GeoFS-Autoland/autopilot-pp
          ref: release

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Build
        run: |
          npm i
          npm run build

      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: autopilot_pp
          path: dist/autopilot_pp.js

  job_6:
    name: Build FMC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: GeoFS-Autoland/fmc-requirejs
          ref: release

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Build
        run: |
          npm i
          npm run build

      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: fmc
          path: dist/fmc.js

  job_7:
    name: Build Spoilers Arming
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: GeoFS-Autoland/spoilers-arming
          ref: release

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Build
        run: |
          npm i
          npm run build

      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: spoilers_arming
          path: dist/spoilers_arming.js

  job_8:
    name: Build Keyboard Mapping
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: GeoFS-Autoland/keyboard-mapping
          ref: release

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Build
        run: |
          npm i
          npm run build

      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: keyboard_mapping
          path: dist/keyboard_mapping.js

  job_9:
    name: Commit scripts
    needs: [job_5, job_6, job_7, job_8]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Download AP++
        uses: actions/download-artifact@v2
        with:
          name: autopilot_pp
          path: source/scripts

      - name: Download FMC
        uses: actions/download-artifact@v2
        with:
          name: fmc
          path: source/scripts

      - name: Download Spoilers Arming
        uses: actions/download-artifact@v2
        with:
          name: spoilers_arming
          path: source/scripts

      - name: Download Keyboard Mapping
        uses: actions/download-artifact@v2
        with:
          name: keyboard_mapping
          path: source/scripts

      - name: Build extension
        run: |
          npm i
          npm run build

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖: Update scripts"
