name: Nightly actions

on:
  workflow_dispatch:

  schedule:
    - cron: "0 2 * * *"

jobs:
  job_1:
    name: Lock old issues and prs
    runs-on: ubuntu-latest

    steps:
      - name: Lock issues
        uses: dessant/lock-threads@v2
        with:
          github-token: ${{ secrets.PAT }}
          issue-exclude-labels: "dependencies"
          issue-lock-labels: "locked"
          pr-lock-labels: "locked"
          issue-lock-inactive-days: 30
          pr-lock-inactive-days: 30
          issue-lock-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for new issues related to this.
          pr-lock-comment: >
            This pull request has been automatically locked since there
            has not been any recent activity after it was closed.
