name: CI

on:
  pull_request:


jobs:
  job_1:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm run build

  job_2:
    name: Test
    needs: job_1
    runs_on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: npm run test