name: PR Tests

on:
  pull_request:

jobs:
  job_1:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'

      - name: Install packages
        run: npm i

      - name: Build
        run: npm run build

  job_2:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'

      - name: Install packages
        run: npm i

      - name: Lint
        run: sudo npx eslint

  job_3:
    name: Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'

      - name: Install packages
        run: npm i

      - name: Audit for vulnerabilities
        run: sudo npx audit-ci --moderate