name: Release

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.5.0"

      - name: Install packages
        run: npm i

      - name: Build
        run: npm run build

      - name: Zip
        uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: extension.zip

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: extension.zip
          draft: true
          tag: latest
          name: NAME THIS ASAP
