name: "Chore: Repackage"

on:
  workflow-dipatch:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  repackage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'

      - name: Repackage
        run: |
          rm -rf node_modules
          npm i
        shell: bash

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git pull
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
          else
            git commit -m "🤖 Chore: Repackage" -a --allow-empty
            echo "::set-output name=push::true"
          fi
          git push
        shell: bash